# Generated by Django 4.1.5 on 2023-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
