version: "3.3"
name: wireguard-django
services:
  backend:
    image: drode1/wireguard_django:latest
    restart: always
    volumes:
      - ../backend/media/:/app/media/
      - ../backend/db.sqlite3:/app/db.sqlite3
      - ../backend/logs:/app/logs
    env_file:
      - ./.env
    container_name: backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../static/:/var/html/static/
      - ../backend/media/:/var/html/media/
    depends_on:
      - backend
    container_name: nginx

volumes:
  media_value:
