# Generated by Django 4.1.5 on 2023-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0002_alter_wireguardinterface_listen_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название ресурса'),
        ),
    ]
