# Generated by Django 4.1.5 on 2023-01-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireguardinterface',
            name='listen_port',
            field=models.PositiveIntegerField(default=51820, verbose_name='Порт'),
        ),
        migrations.AlterField(
            model_name='wireguardinterface',
            name='name',
            field=models.CharField(default='wg0', max_length=128, unique=True, verbose_name='Название интерфейса'),
        ),
        migrations.AlterField(
            model_name='wireguardinterface',
            name='private_key',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Приватный ключ'),
        ),
        migrations.AlterField(
            model_name='wireguardinterface',
            name='public_key',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Публичный ключ'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='private_key',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Приватный ключ'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='public_key',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Публичный ключ'),
        ),
    ]
