# Generated by Django 4.1.5 on 2023-01-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
